export interface WordEntry {
  word: string;
  category: string;
}

export const WORDS: WordEntry[] = [
  // Naturaleza
  { word: "Guepardo", category: "Naturaleza" },
  { word: "Galaxia", category: "Naturaleza" },
  { word: "Cascada", category: "Naturaleza" },
  { word: "Volcán", category: "Naturaleza" },
  { word: "Océano", category: "Naturaleza" },
  { word: "Selva", category: "Naturaleza" },
  { word: "Estrella", category: "Naturaleza" },
  { word: "Arrecife", category: "Naturaleza" },
  { word: "Glaciar", category: "Naturaleza" },
  { word: "Planeta", category: "Naturaleza" },
  { word: "Huracán", category: "Naturaleza" },
  { word: "Arcoíris", category: "Naturaleza" },
  { word: "Montaña", category: "Naturaleza" },
  { word: "Desierto", category: "Naturaleza" },
  { word: "Bosque", category: "Naturaleza" },
  { word: "Pantano", category: "Naturaleza" },
  { word: "Jungla", category: "Naturaleza" },
  { word: "Pradera", category: "Naturaleza" },
  { word: "Cueva", category: "Naturaleza" },
  { word: "Remolino", category: "Naturaleza" },
  
  // Escuela
  { word: "Experimento", category: "Escuela" },
  { word: "Telescopio", category: "Escuela" },
  { word: "Biblioteca", category: "Escuela" },
  { word: "Geometría", category: "Escuela" },
  { word: "Diccionario", category: "Escuela" },
  { word: "Microscopio", category: "Escuela" },
  { word: "Historia", category: "Escuela" },
  { word: "Laboratorio", category: "Escuela" },
  { word: "Ajedrez", category: "Escuela" },
  { word: "Creatividad", category: "Escuela" },
  { word: "Matemáticas", category: "Escuela" },
  { word: "Literatura", category: "Escuela" },
  { word: "Geografía", category: "Escuela" },
  { word: "Escritura", category: "Escuela" },
  { word: "Pizarrón", category: "Escuela" },
  { word: "Mochila", category: "Escuela" },
  { word: "Recreo", category: "Escuela" },
  { word: "Cuaderno", category: "Escuela" },
  { word: "Pincel", category: "Escuela" },
  { word: "Aprender", category: "Escuela" },
  
  // Hogar
  { word: "Videojuego", category: "Hogar" },
  { word: "Cumpleaños", category: "Hogar" },
  { word: "Bicicleta", category: "Hogar" },
  { word: "Televisión", category: "Hogar" },
  { word: "Instrumento", category: "Hogar" },
  { word: "Colección", category: "Hogar" },
  { word: "Juguete", category: "Hogar" },
  { word: "Desayuno", category: "Hogar" },
  { word: "Familia", category: "Hogar" },
  { word: "Merienda", category: "Hogar" },
  { word: "Cocinero", category: "Hogar" },
  { word: "Dormitorio", category: "Hogar" },
  { word: "Ventana", category: "Hogar" },
  { word: "Jardín", category: "Hogar" },
  { word: "Almohada", category: "Hogar" },
  { word: "Espejo", category: "Hogar" },
  { word: "Carpintero", category: "Hogar" },
  { word: "Arquitectura", category: "Hogar" },
  { word: "Escalera", category: "Hogar" },
  { word: "Bombilla", category: "Hogar" },
  
  // Fantasía
  { word: "Dinosaurio", category: "Fantasía" },
  { word: "Hechizo", category: "Fantasía" },
  { word: "Dragón", category: "Fantasía" },
  { word: "Unicornio", category: "Fantasía" },
  { word: "Caballero", category: "Fantasía" },
  { word: "Castillo", category: "Fantasía" },
  { word: "Aventura", category: "Fantasía" },
  { word: "Leyenda", category: "Fantasía" },
  { word: "Sirena", category: "Fantasía" },
  { word: "Gigante", category: "Fantasía" },
  { word: "Centauro", category: "Fantasía" },
  { word: "Poción", category: "Fantasía" },
  { word: "Tesoro", category: "Fantasía" },
  { word: "Pirata", category: "Fantasía" },
  { word: "Fantasma", category: "Fantasía" },
  { word: "Esqueleto", category: "Fantasía" },
  { word: "Antifaz", category: "Fantasía" },
  { word: "Laberinto", category: "Fantasía" },
  { word: "Invisible", category: "Fantasía" },
  { word: "Relámpago", category: "Fantasía" },
  
  // Animales
  { word: "Elefante", category: "Animales" },
  { word: "Cocodrilo", category: "Animales" },
  { word: "Hipopótamo", category: "Animales" },
  { word: "Jirafa", category: "Animales" },
  { word: "Tiburón", category: "Animales" },
  { word: "Delfín", category: "Animales" },
  { word: "Ballena", category: "Animales" },
  { word: "Canguro", category: "Animales" },
  { word: "Tortuga", category: "Animales" },
  { word: "Camaleón", category: "Animales" },
  { word: "Murciélago", category: "Animales" },
  { word: "Avestruz", category: "Animales" },
  { word: "Pingüino", category: "Animales" },
  { word: "Mariposa", category: "Animales" },
  { word: "Escarabajo", category: "Animales" },
  { word: "Calamar", category: "Animales" },
  { word: "Flamenco", category: "Animales" },
  { word: "Ornitorrinco", category: "Animales" },
  { word: "Luciérnaga", category: "Animales" },
  { word: "Escorpión", category: "Animales" },

  // Espacio
  { word: "Astronauta", category: "Espacio" },
  { word: "Cohete", category: "Espacio" },
  { word: "Meteorito", category: "Espacio" },
  { word: "Satélite", category: "Espacio" },
  { word: "Cometa", category: "Espacio" },
  { word: "Mercurio", category: "Espacio" },
  { word: "Eclipse", category: "Espacio" },
  { word: "Universo", category: "Espacio" },
  { word: "Nebulosa", category: "Espacio" },
  { word: "Asteroide", category: "Espacio" },
  { word: "Telescopio", category: "Espacio" },
  { word: "Gravedad", category: "Espacio" },
  { word: "Cosmos", category: "Espacio" },
  { word: "Saturno", category: "Espacio" },
  { word: "Constelación", category: "Espacio" },

  // Deportes
  { word: "Fútbol", category: "Deportes" },
  { word: "Baloncesto", category: "Deportes" },
  { word: "Natación", category: "Deportes" },
  { word: "Ciclismo", category: "Deportes" },
  { word: "Patinaje", category: "Deportes" },
  { word: "Atletismo", category: "Deportes" },
  { word: "Esgrima", category: "Deportes" },
  { word: "Béisbol", category: "Deportes" },
  { word: "Gimnasia", category: "Deportes" },
  { word: "Voleibol", category: "Deportes" },
  { word: "Raqueta", category: "Deportes" },
  { word: "Medalla", category: "Deportes" },
  { word: "Campeón", category: "Deportes" },
  { word: "Entrenar", category: "Deportes" },
  { word: "Esfuerzo", category: "Deportes" },

  // Valores
  { word: "Valentía", category: "Valores" },
  { word: "Gratitud", category: "Valores" },
  { word: "Respeto", category: "Valores" },
  { word: "Amistad", category: "Valores" },
  { word: "Bondad", category: "Valores" },
  { word: "Esfuerzo", category: "Valores" },
  { word: "Honestidad", category: "Valores" },
  { word: "Justicia", category: "Valores" },
  { word: "Empatía", category: "Valores" },
  { word: "Paciencia", category: "Valores" },
  { word: "Solidaridad", category: "Valores" },
  { word: "Libertad", category: "Valores" },
  { word: "Humildad", category: "Valores" },
  { word: "Optimismo", category: "Valores" },
  { word: "Generosidad", category: "Valores" },
  { word: "Sinceridad", category: "Valores" },
  { word: "Tolerancia", category: "Valores" },
  { word: "Perseverancia", category: "Valores" }
];
